name: CustomerSegment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pip=25.0.1
  - pandas=2.2.3
  - numpy=1.26.4
  - pyarrow=19.0.1
  - fastparquet=2024.11.0
  - scikit-learn=1.6.1
  - statsmodels=0.14.4
  - xgboost=2.1.4
  - lightgbm=4.6.0
  - catboost=1.2.7
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - ipykernel=6.29.5
  - notebook=7.3.3
  - jupyterlab=4.3.6
  - tqdm=4.67.1
  - pip:
      - optuna==4.2.1
